### ISSUE TITLE
Please add Teignbridge Council

### ISSUE THREAD

**Issue by Sanpeds** [robbrad/UKBinCollectionData#633] opened 2024-03-13 23:53 UTC
### Name of Council

Teignbridge District Council 

### Example Address/Postcode

Dunmore Residential Home, 28-30 Courtenay Road, NEWTON ABBOT, TQ12 1HE

### Additional Information

Lookup is available here:
https://www.teignbridge.gov.uk/recycling-and-waste/waste-and-recycling-collections/when-are-my-bins-and-boxes-collected/

Pre filled lookup for bin collection for above address:
https://www.teignbridge.gov.uk/recycling-and-waste/waste-and-recycling-collections/when-are-my-bins-and-boxes-collected/?UPRN=100040318955

A collection calendar is also available:
https://www.teignbridge.gov.uk/recycling-and-waste/waste-and-recycling-collections/download-your-collection-calendar/

The black and green recycling boxes go out each week, as does the food waste and paper sack. Black (landfill) and green (garden waste) are on alternative weeks. Note that not all houses have the green bin since this is a paid extra, for those houses the black bin is still once every 2 weeks.

The lookup tool works quite well. It can remember an address and also adjusts for changes to the pickup dates based on bank holiday etc. 

Thanks for looking at this! 

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-03-14 00:20
Duplicate of #580, but thanks for the extra tips 😊

**Closed by dp247** 2024-03-14 00:20 UTC
Labels: council request

**Comment by Sanpeds** [comment] 2024-03-14 06:48
Apologies, didn't see that it had already been raised! My searching seeds some extra work!
