### ISSUE TITLE
Teignbridge Council Request

### ISSUE THREAD

**Issue by astent24** [robbrad/UKBinCollectionData#874] opened 2024-10-10 19:56 UTC
### Name of Council

Teignbridge District Council 

### Example Address/Postcode

TQ12 6BT 

### Additional Information

https://www.teignbridge.gov.uk/recycling-and-waste/waste-and-recycling-collections/when-are-my-bins-and-boxes-collected/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-10-10 22:48
Duplicate of #580

**Closed by dp247** 2024-10-10 22:48 UTC
Labels: council request
