### ISSUE TITLE
Sefton Council

### ISSUE THREAD

**Issue by JonZso** [robbrad/UKBinCollectionData#899] opened 2024-10-18 10:39 UTC
### Name of Council

Sefton Council

### Example Address/Postcode

PR8 4PL

### Additional Information

https://sefton.gov.uk/

https://www.sefton.gov.uk/bins-and-recycling/bins-and-recycling/when-is-my-bin-collection-day/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by JonZso** [comment] 2024-10-18 10:40
Duplicate

**Comment by dp247** [comment] 2024-10-18 11:14
Duplicate of #770

**Closed by dp247** 2024-10-18 11:14 UTC
Labels: council request
