### ISSUE TITLE
West Oxfordshire District Council

### ISSUE THREAD

**Issue by XavierUK** [robbrad/UKBinCollectionData#843] opened 2024-10-06 09:08 UTC
### Name of Council

West Oxfordshire District Council

### Example Address/Postcode

OX28 4AE

### Additional Information

https://community.westoxon.gov.uk/s/waste-collection-enquiry
[2024-25-wodc-thursday-1.pdf](https://github.com/user-attachments/files/17268740/2024-25-wodc-thursday-1.pdf)

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-10-06 09:54
Duplicate of #694

**Closed by dp247** 2024-10-06 09:54 UTC
Labels: council request
