### ISSUE TITLE
Babergh Council request

### ISSUE THREAD

**Issue by captain-ted** [robbrad/UKBinCollectionData#919] opened 2024-10-22 16:30 UTC
Name of the council - Babergh District Council
URL to bin collections
Refuse and recycling - https://www.babergh.gov.uk/w/check-your-collection-day
Garden waste - https://www.babergh.gov.uk/w/check-your-collection-day#check-your-garden-waste-collection-day
An example postcode and/or UPRN (whichever is relevant) - CO6 4RA
Any further information - general refuse, recycling and garden waste collections

**Comment by SingingDwarf** [comment] 2024-11-06 13:40
This looks like a dupe of #868

**Comment by robbrad** [comment] 2024-11-06 15:03
Duplicate request

**Comment by captain-ted** [comment] 2024-11-06 15:30
Hi,

If a duplicate, this is the right course of action but want to make sure - Babergh and Mid Suffolk are different district councils. My request was focussing on Babergh.

Many thanks

On 6 Nov 2024, at 15:04, Robert Bradley ***@***.***> wrote:

﻿

Closed #919<https://github.com/robbrad/UKBinCollectionData/issues/919> as not planned.

**Comment by captain-ted** [comment] 2024-11-06 20:38
> Duplicate request

Have looked - not a duplicate. Babergh and Mid Suffolk are different councils. Please could you reinstate the ticket @robbrad ?

**Comment by captain-ted** [comment] 2024-11-06 20:50
Thanks @dp247 . The councils are closely linked and so there’s a chance that integrating one may solve integrating the other but they are to my knowledge different councils and they have different websites .

**Comment by robbrad** [comment] 2024-11-06 22:39
> > Duplicate request
> 
> 
> 
> Have looked at the linked ticket - not a duplicate. Babergh and Mid Suffolk are different councils. Please could you reinstate the ticket @robbrad @SingingDwarf ?

Sorry @captain-ted 

I think the confusion is your request mentions and Mid Suffolk and there is already a ticket for that.

This looks like it's one of the same and not two.

For clarity I'll rename this ticket to be Babergh only but put a link to Mid Suffolk

Not in our system even if they are the same implementation at the council end they will be distinct in this project.

**Closed** 2024-11-12 06:00 UTC
Labels: council request
