### ISSUE TITLE
Plymouth City Council

### ISSUE THREAD

**Issue by luconnet** [robbrad/UKBinCollectionData#820] opened 2024-09-30 15:53 UTC
### Name of Council

Plymouth City Council

### Example Address/Postcode

PL3 4LW

### Additional Information

Website: https://www.plymouth.gov.uk/check-your-bin-day

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-09-30 16:09
Duplicate of #566

**Closed by dp247** 2024-09-30 16:09 UTC
Labels: council request
