### ISSUE TITLE
Teignbridge District Council

### ISSUE THREAD

**Issue by glendower** [robbrad/UKBinCollectionData#762] opened 2024-06-27 10:58 UTC
### Name of Council

Teignbridge District Council

### Example Address/Postcode

tq125hd

### Additional Information

https://www.teignbridge.gov.uk/recycling-and-waste/waste-and-recycling-collections/when-are-my-bins-and-boxes-collected/?UPRN=100040327017

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-06-27 17:50
Duplicate of #580

**Closed by dp247** 2024-06-27 17:50 UTC
Labels: council request
