### ISSUE TITLE
Chesterfield Borough Council Request

### ISSUE THREAD

**Issue by vipermk2** [robbrad/UKBinCollectionData#952] opened 2024-11-02 10:43 UTC
### Name of Council

Chesterfield Borough Counci

### Example Address/Postcode

S40 2RE

### Additional Information

https://www.chesterfield.gov.uk/bins-and-recycling/bin-collections/check-bin-collections

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-11-02 10:56
Duplicate of #718

**Closed by dp247** 2024-11-02 10:56 UTC
Labels: council request
