### ISSUE TITLE
Entity No Longer Being Provided 

### ISSUE THREAD

**Issue by bobat-h** [robbrad/UKBinCollectionData#429] opened 2023-11-18 13:53 UTC
### Name of Council

Bolton

### Issue Information

The entities are no longer being provided, i have tried to re add but still no entities showing up. I have tried a different address but same issue persists. This is the test uprn i used '100010886949|21 HEATON AVENUE, BOLTON, BL1 5PQ'.

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by alexforrow** [comment] 2023-11-22 10:39
The issue appears to be that underlying library isn't returning any data. Ideally the integration would mark the entity as as unavailable or similar.

```poetry run python uk_bin_collection/uk_bin_collection/collect_data.py BoltonCouncil https://www.bolton.gov.uk/next-bin-collection -s -u 100010886949
{
    "bins": []
}```

**Comment by dandantheitman** [comment] 2023-11-29 12:12
Looks like the cause is that the council has changed how their site works so the scraper no longer works. I've patched it locally to get mine working again after stealing some code from the Wigan council scraper, will try and get the changes into a branch along with the updates for the tests and wiki (now needs UPRN and postcode instead of UPRN|Address).

**Comment by dp247** [comment] 2023-11-29 12:25
> Looks like the cause is that the council has changed how their site works so the scraper no longer works. I've patched it locally to get mine working again after stealing some code from the Wigan council scraper, will try and get the changes into a branch along with the updates for the tests and wiki (now needs UPRN and postcode instead of UPRN|Address).

If you need any help, just give me a ping

**Comment by dandantheitman** [comment] 2023-11-29 13:20
Thanks @dp247. Pull request is there now after figuring out how to set up github auth properly, that felt more complex than the actual scraper fix.

**Comment by dandantheitman** [comment] 2023-11-30 15:55
Issue can probably be marked resolved now. Fix has been merged into master. Anyone already using Bolton council will need to update, remove their current integration and then add it again. If you updated correctly then it will now ask for your postcode when adding the integration. Once that's done the entity no longer being provided errors should be resolved, at least they are for me.

**Comment by dp247** [comment] 2023-12-01 07:05
Closing for now

**Closed** 2023-12-01 07:04 UTC
Labels: bug
