### ISSUE TITLE
UK | Brighton and Hove - Request

### ISSUE THREAD

**Issue by Akiva-J** [robbrad/UKBinCollectionData#504] opened 2023-12-27 16:50 UTC
### Name of Council

Brighton and Hove 

### Example Address/Postcode

UPRN: 22060199 / 124 Carden Avenue / BN1 8NE

### Additional Information

https://cityclean.brighton-hove.gov.uk/link/collections

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by robbrad** [comment] 2023-12-29 18:25
Duplicate of #188

**Comment by robbrad** [comment] 2024-01-01 09:05
Released

**Closed by robbrad** 2024-01-01 09:05 UTC
Labels: council request

**Comment by Akiva-J** [comment] 2024-01-02 13:17
> Released

Thanks so much for doing this. 
I can't see my council listed in the UI when setting up the integration. 
![image](https://github.com/robbrad/UKBinCollectionData/assets/78052249/5e604e3a-199b-4493-87b2-7130e644ef12)


I assume I have to set it up manually. 
However, I'm pretty new to python and scripts on Home assistant. 
So currently looking at this and confused.
https://github.com/robbrad/UKBinCollectionData/wiki/Councils#brighton-and-hove-city-council

Is there a guide I can follow somewhere?
