### ISSUE TITLE
Chesterfield Borough Council

### ISSUE THREAD

**Issue by cpass-watch** [robbrad/UKBinCollectionData#774] opened 2024-07-28 09:12 UTC
### Name of Council

Chesterfield Borough Council

### Example Address/Postcode

S41 0NJ

### Additional Information

UPRN: 74043600

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-07-31 22:06
Duplicate of #718

**Closed by dp247** 2024-07-31 22:06 UTC
Labels: council request
