### ISSUE TITLE
Teignbridge District Council 

### ISSUE THREAD

**Issue by glendower** [robbrad/UKBinCollectionData#765] opened 2024-07-01 09:33 UTC
### Name of Council

Teignbridge District Council

### Issue Information

Teignbridge District Council

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have checked my address/postcode/UPRN works on the council's website
- [X] I have provided a detailed explanation of the issue as well as steps to replicate the issue
- [X] I understand that this project is run by volunteer contributors therefore completion of this issue cannot be guaranteed

**Comment by digdilem** [comment] 2024-10-03 20:08
I would also like to see Teignbridge District Council added. 

(Not sure why this has BUG labelled instead of Council Request?)

**Comment by dp247** [comment] 2024-10-03 20:38
> (Not sure why this has BUG labelled instead of Council Request?)

Didn't even consider if it existed or not since we have a standard request issue template 🤣

**Comment by glendower** [comment] 2024-10-04 09:57
Hi
It's labelled as a bug since teighmouth has supposedly been added but I am unable to find it 
I did initially submit a council request and the reply was that it had already been added

⁣Get BlueMail for Android ​

**Comment by dp247** [comment] 2024-10-04 10:10
I see what's happened now. Someone has already opened a request for it, so that's why the other requests have been closed, as we try to have only one issue request per council.
I'll close this as a duplicate of #580 - it won't be added until someone writes the scraper for it, but if you subscribe to the linked issue, you'll be notified when it closes.

**Closed by dp247** 2024-10-04 10:10 UTC
Labels: council request

**Comment by glendower** [comment] 2024-10-05 10:45
So will Teighmouth finally be added?

⁣Get BlueMail for Android ​

**Comment by dp247** [comment] 2024-10-05 11:01
I'm not sure I appreciate the tone of "_finally_" lol. It will be added when someone writes the code for it, that's how a project like this works. It doesn't need re-requesting, that won't speed it up. 😊

**Comment by glendower** [comment] 2024-10-05 21:19
Hi David
I'm sorry if my last post came over as disrespectful, that was not my intent and I apologise unreservedly.
When I initially looked in the drop down menu Teignbridge council was not available, I checked the requests and a request for Teighbridge was made on Jan 16 #580 and from what I could see all the necessary information had been supplied.
Because I couldn't find it I assumed there must be a bug.
If the supplied data in the original request is incorrect let me know and I will resubmit
Again sorry for the tone in my last post.
Pete
Get BlueMail <https://bluemail.me> for Desktop
David Park wrote:
I'm not sure I appreciate the tone of "finally" lol. It will be added when someone writes the code for it, that's how a project like this works. It doesn't need re-requesting, that won't speed it up. 😊
