### ISSUE TITLE
Please add Ashfield District Council

### ISSUE THREAD

**Issue by TheViinnn** [robbrad/UKBinCollectionData#922] opened 2024-10-22 19:42 UTC
### Name of Council

Ashfield District Council

### Example Address/Postcode

NG15 6EW

### Additional Information

https://www.ashfield.gov.uk/environment-health/bins-waste-recycling/bin-calendar/

### Verification

- [X] I searched for similar issues at https://github.com/robbrad/UKBinCollectionData/issues?q=is:issue and found no duplicates
- [X] I have provided a tested working address/postcode/UPRN with bin collections available
- [X] I understand that this project is run by volunteer contributors and completion depends on numerous factors - even with a request, we cannot guarantee if/when your council will get a script

**Comment by dp247** [comment] 2024-10-24 11:45
Duplicate of #579

**Closed by dp247** 2024-10-24 11:45 UTC
Labels: council request
